### ISSUE TITLE
Coding styleguide and linting for JavaScript

### ISSUE THREAD

**Issue by FrancescoK** [eHealthAfrica/eHealthAfrica.github.io#20]
Suggestion:
- Adopt ESLint over JSHint+JSCS to have one tool only
- Use ESLint [standard rulesets](http://eslint.org/docs/rules/), similar to what JSHint and JSCS provide
- Set linting infringements to errors and style infringements to warnings, break build on error (linting) but not on warning (style)
- Keep rather loose styleguide

Discussion:
- Adopt [mgechev’s Angular styleguide](https://github.com/mgechev/angularjs-style-guide)? Was suggested/used in some projects.

Other options: 
- [standard](https://www.npmjs.com/package/standard)
- [semi-standard](https://www.npmjs.com/package/semistandard) (tl;dr semicolons!)
- [Idiomatic.js](https://github.com/rwaldron/idiomatic.js) or the [Google styleguide](http://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml),
- [Pragmatic.js](https://github.com/stevekwan/best-practices/blob/master/javascript/best-practices.md)
- etc.

**Comment by tthew** [comment]
:+1: on all points apart from [mgechev’s Angular styleguide](https://github.com/mgechev/angularjs-style-guide) which I have a bunch of problems with.

**Comment by tthew** [comment]
I think I'd prefer to put together a style guide / best practise based on experience our own experience.

**Comment by FrancescoK** [comment]
@tthew: Do you want to take a stab at it with a first minimal version as PR to the docs? That could be a ground for discussion. I could help with a first suggested structure but could not provide the content ;)

**Comment by danse** [comment]
Please, if possible, let us not reinvent also this wheel. We have got quite some options to choose from:
- https://github.com/airbnb/javascript
- http://google.github.io/styleguide/javascriptguide.xml
- https://contribute.jquery.org/style-guide/js/
- https://github.com/ExactTarget/javascript

And counting ... just pick one

**Comment by rmehner** [comment]
My two cents: Pick one of the existing, stick to it. If it's really annoying the majority of us, we still can adapt. But I don't see this being a big task. It's just characters in textfiles, get over it :P

**Comment by tthew** [comment]
@danse, @rmehner, totally agree with regard to js style.  But for angular specific stuff; `mgechev’s Angular styleguide` is not the way to go.

**Comment by tthew** [comment]
Perhaps that should be part of a seperate issue.  Angular best practises != style guide.

**Comment by tthew** [comment]
Just to clarify;

> I think I'd prefer to put together a style guide / best practise based on experience our own experience.

I was referring _specifically_ to angular style / best practise.  Sorry I didn't make that clear.

**Comment by tthew** [comment]
But also on that point. I don't buy into just jumping on a community 'because community'.  Just because there is 'Status Quo' doesn't mean we have to or should accept it.

**Comment by FrancescoK** [comment]
Let’s break out the Angular best practices from this issue then. Opening separate one and adjusting the description here accordingly.

**Comment by FrancescoK** [comment]
Only issue is that most existing Angular style guides try to cover non-Angular-specific parts as well, which would be conflicting.

**Comment by rmehner** [comment]
> But also on that point. I don't buy into just jumping on a community 'because community'. Just because there is 'Status Quo' doesn't mean we have to or should accept it.

I just want to ensure that we don't bikeshed us into oblivion ;) As for ESLint I'd propose to simply use one of the community things, use it for a while and if there's something that really annoys us, adapt the default `.eslintrc`. Ain't that hard and no use for discussing this over and over, we have 20+ people in this project and key is consistency :)

**Comment by rmehner** [comment]
As for Angular: @tthew, you had this nice seed project, are the conventions for that somewhat formalized? Would love to adapt those.

**Comment by tthew** [comment]
I think we were talking at crossed purposes.  I totally buy into using a community based lint/style template.  But so far as how we should build angular apps I've got plenty of opinions if anyone's short :dancer: 

This is the seed I put together tail end of last year; https://github.com/tthew/gulp-angular-webpack-seed, it was really just a culmination of my thoughts / experience building angular apps for the 2 years prior to that (making lots of mistakes along the way). But in general this is mostly still in line with my current thinking. (some implementation preferences may have changed, like I would favour `angular-i18n` or `angular-gettext` over `angular-translate` now). But I still stand by the _general_ approach to architecture (with some conversation points)

_edit - [mnutrition-app](https://github.com/eHealthAfrica/mnutrition-app) is also a good example_

**Comment by jjal** [comment]
bungee contribution, pls see prior work on this: https://github.com/eHealthAfrica/LMIS-Chrome/wiki/Coding-Conventions

**Comment by tlvince** [comment]
+1 on ESLint and +1 on reusing a popular style guide. I would suggest we drop in the [eslint-config-airbnb](https://www.npmjs.com/package/eslint-config-airbnb) config and embellish it with our own [shareable config](http://eslint.org/docs/developer-guide/shareable-configs) _if_ necessary (they're easy to do, e.g. [eslint-config-tlvince](https://github.com/tlvince/eslint-config-tlvince), but we should try to avoid it).

For Angular-specific rules, I've had some milage with [eslint-plugin-angular](https://github.com/Gillespie59/eslint-plugin-angular).

**Comment by jo** [comment]
:+1:  standard

**Comment by gr2m** [comment]
`+1` for `standard`. I don't like all the conventions in there, but I like the fact that it's a zero-configuration setup. It's just a solved problem for me, I don't need to think about code style anymore. And I think that fits our culture pretty well at eHealth, we have more important stuff to focus on than indentation and semicolons

**Comment by febeling** [comment]
Standard looks good to me too. How can we decide this?

**Comment by tthew** [comment]
We're using (semi-)standard on more recent projects i.e polio-dashboard (which actually just wraps eslint afaik any way).  

I think we're mostly settled on (semi-)standard.  The question is:

> To semi-colon or not

**Comment by rmehner** [comment]
> To semi-colon or not

`standard` has a nice rule for this. Let's stick with this and get rid of the semicolons. standard warns for the one case where stuff would break, we only have to use it and include it in CI.

**Comment by jo** [comment]
:+1:

**Comment by gr2m** [comment]
yes please let's do `standard`? Let's bribe the critiques with cheese cake!

**Comment by rmehner** [comment]
I’d say: Stop discussing, just let’s  use it. The benefits outweigh opinions :)

**Comment by patriciagarcia** [comment]
I am not against `standard` per se but I remember that once we had a bug in production when minifying because a file didn't have a semicolon at the end (#juststandardthings), and it was mixing with the next module. Very difficult and frustrating to debug, ask @tthew ;). 

Now we're inserting semi-colons when minifying, but that sounds a little bit error prone to me, unless we standardize the `Gruntfile` too. Maybe we should do that?

**Comment by tthew** [comment]
I'm not going to try to block this. I've had bad experiences. But if everyone except me is confident that this is the right way to go then let's do it.

**Comment by tthew** [comment]
But one thing; this is going to require refactoring a lot of existing code.

**Comment by gr2m** [comment]
> this is going to require refactoring a lot of existing code

`standard --format` will do the most of the heavy lifting I think. I tried it in the [kazana](https://github.com/eHealthAfrica/kazana) repo. `standard --format` did all the work, no manual adjustments needed. Might be a bit more work in other repos, but we just did a similar migrations on a lot of Hoodie repos, and it worked pretty well

**Comment by FrancescoK** [comment]
Decision on Tech Talk Tuesday August 18th: `standard` it is.
