### ISSUE TITLE
 README styleguide

### ISSUE THREAD

**Issue by jo** [eHealthAfrica/eHealthAfrica.github.io#31]
As [proposed by @skoni](https://github.com/eHealthAfrica/sense-dispatch/pull/5#issuecomment-134542059) we should standardise our REAMDEs, especially the ones used for our internal services.

I suggest we include an outline in the Coding Styleguides.

Eg:
1. Name
2. Description
3. Code snippet or usage example
4. Installation
5. Detailed usage
6. Testing
7. License

For further research [awesome-readme](https://github.com/matiassingers/awesome-readme) lists some examples of good READMEs as well as some articles about writing them.

**Comment by jo** [comment]
http://jfhbrook.github.io/2011/11/09/readmes.html is a good reading:
1. Write an Example, Right Now
2. Describe the install procedure.
3. Stub out the API docs.
4. Tests
5. Licensing and Contributors

**Comment by jo** [comment]
ping @skoni ;)

**Comment by tillre** [comment]
Your list and the one from Joshua Holbrook are pretty similar. I like them both. For me the important parts are a short description and the example usage, because i think that matters most to people who do not modify the code, but just integrate it.

**Comment by jo** [comment]
Yes - and sorry, was meant to ping you about the pull https://github.com/eHealthAfrica/eHealthAfrica.github.io/pull/32 :)

**Comment by FrancescoK** [comment]
@jo Would it be valuable to also have some dotfiles-like repo for setup or some project–specific setup shell scripts?

**Comment by jo** [comment]
For me personally I think its best to just keep it in hand-muscle-memory. Because one always forget to keep those templates up to date.

**Comment by tthew** [comment]
@jo 

Seeings as #32  this has already been merged, can we consider this is a done deal and close this ticket?

**Comment by FrancescoK** [comment]
I’d say so.
