### ISSUE TITLE
Add Guinea

### ISSUE THREAD

**Issue by cristinasantamarina** [eHealthAfrica/eHealthAfrica.github.io#35]
Guinea is missing from everywhere! 

eHealth Africa Guinea
Zein Building, Apt 8B, 
Quartier Almamya, Kaloum, 
BP: 4017, Conakry, Guinea

**Comment by ribalba** [comment]
@cristinasantamarina totally true, really sorry

**Comment by admbtlr** [comment]
Thanks @cristinasantamarina. Is there a guinea@ email address?

**Comment by cristinasantamarina** [comment]
Finding out. If there is not we should create it. Brb with answers.

On Monday, 25 January 2016, adamvert notifications@github.com wrote:

> Thanks @cristinasantamarina https://github.com/cristinasantamarina. Is
> there a guinea@ email address?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/eHealthAfrica/eHealthAfrica.github.io/issues/35#issuecomment-174453214
> .

## 

Cristina Santamarina
Information Systems Advisor
Global Health Informatics Department
DE: +49 152 5976 9344
GN: +224 62 4196 370
cristina.santamarina@ehealthafrica.org
www.ehealthafrica.org

**Comment by admbtlr** [comment]
Guinea snail mail added, along with new GHI email address
